In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6]

In [3]:
lista

[1, 2, 3, 4, 5, 6]

In [5]:
arreglo = np.array(lista)

In [6]:
arreglo

array([1, 2, 3, 4, 5, 6])

In [7]:
arreglo[0]

1

In [8]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
ale = np.random.randint(0,69,50)

In [13]:
ale

array([47, 30, 48,  0, 25, 10, 23, 20, 11, 45, 55, 48, 38, 49, 56, 56, 66,
        8, 60,  0, 66, 49, 21,  9, 68, 61, 18, 34, 29, 38, 64, 37, 64, 15,
       26, 61, 22, 40, 39, 16, 60,  3, 54,  1,  3, 55, 60, 17, 18,  5])

In [14]:
ale.max()

68

In [15]:
ale.min()

0

In [16]:
ale.argmax()

24

In [17]:
ale.argmin()

3

In [19]:
ale = ale.reshape(5,10)

In [20]:
ale

array([[47, 30, 48,  0, 25, 10, 23, 20, 11, 45],
       [55, 48, 38, 49, 56, 56, 66,  8, 60,  0],
       [66, 49, 21,  9, 68, 61, 18, 34, 29, 38],
       [64, 37, 64, 15, 26, 61, 22, 40, 39, 16],
       [60,  3, 54,  1,  3, 55, 60, 17, 18,  5]])