In [18]:
import numpy as np

In [19]:
lista = [1,2,3,4,5,6]

In [20]:
lista

[1, 2, 3, 4, 5, 6]

In [21]:
arreglo = np.array(lista)

In [22]:
arreglo

array([1, 2, 3, 4, 5, 6])

In [23]:
arreglo[0]

1

In [24]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
ale = np.random.randint(0,69,50)

In [28]:
ale

array([41, 50, 66, 12, 36, 30, 30, 25, 11, 28, 47, 11, 35, 35, 42, 52, 20,
       16, 60, 40, 15,  7, 17,  9, 37, 17,  9,  4, 64, 52, 59, 43, 65,  9,
       41, 63,  4, 10, 68, 32, 57, 22, 68, 62, 58,  5, 47, 59, 28, 56])

In [29]:
ale.max()

68

In [30]:
ale.min()

4

In [31]:
ale.argmax()

38

In [32]:
ale.argmin()

27

In [33]:
ale = ale.reshape(5,10)

In [34]:
ale

array([[41, 50, 66, 12, 36, 30, 30, 25, 11, 28],
       [47, 11, 35, 35, 42, 52, 20, 16, 60, 40],
       [15,  7, 17,  9, 37, 17,  9,  4, 64, 52],
       [59, 43, 65,  9, 41, 63,  4, 10, 68, 32],
       [57, 22, 68, 62, 58,  5, 47, 59, 28, 56]])